### ISSUE TITLE
Error of unknown source (Bug when switching gamemodes?)

### ISSUE THREAD

**Issue by Andre601** [VolmitSoftware/Mortar#9] opened 2019-07-30 19:56 UTC
### Description
I retrieve the following error for no real reason. I can just assume it has to do with switching gamemode considering I change gamemode of a player on the server and the error happening right after it.

### Error
> \>.... [21:42:08 INFO]: CONSOLE issued server command: /gamemode survival MHF_GitHub
\>.... [21:42:08 INFO]: Set game mode survival for MHF_GitHub.
\>.... [21:42:39 WARN]: [Mortar] Plugin Mortar v1.0.70 generated an exception while executing task 534
java.util.ConcurrentModificationException: null
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_212]
at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_212]
at mortar.lang.collection.GList.copy(GList.java:653) ~[?:?]
at com.volmit.gloss.controllers.EmojiController.reload(EmojiController.java:195) ~[?:?]
at com.volmit.gloss.controllers.EmojiController.lambda$load$0(EmojiController.java:182) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-146]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-146]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-146]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

### Stats and Info
- Plugins:
  - AdvancedCustomItemAPI
  - AdvancedCustomMenu
  - AdvancedModreq*
  - Animatronics*
  - ArmorStandTools
  - BannerBoard*
  - BKCommonLib
  - DeluxeChat
  - DeluxePlugins*
  - DiscordSRV
  - Essentials
  - EssentialsSpawn
  - Gloss*
  - HeadDatabase*
  - HelpPagePlus
  - InfoHeads
  - ItemsAdder
  - LuckPerms
  - Maplands
  - MessageAnnouncer
  - MiniaturePets*
  - Mortar*
  - PlaceholderAPI*
  - ProtocolLib*
  - QuickShop
  - ServerListPlus
  - Vault
  - WarpSystem
  - WorldEdit
  - WorldGuard
- Server
  - PaperMC 1.14.4 (Build 146)
- Mortar Version
  - 1.0.70
- Dependencies of Mortar
  - Gloss 1.3.0

### Additional info
When changing json files (e.g. a hologram file) in Gloss does the plugin suddenly load all emojis again while it didn't do this before.
Only change made from before the error and now was updating the plugin AdvancedModReq to the latest version on Spigot.

**Comment by NextdoorPsycho** [comment] 2019-07-30 20:35
Full log, please

**Comment by DavidRockin** [comment] 2019-07-30 20:37
Please compress all configuration files in a zip and send it. Is the player near a hologram, does it occur when a player is not near a hologram? If it persists near a specific hologram please include that hologram's configuration file aswell. Are you using emojis in boards?

**Comment by DavidRockin** [comment] 2019-07-30 20:39
Possibly a duplicate of https://github.com/VolmitSoftware/Gloss/issues/81 (similar stacktrace in their video)

**Comment by Andre601** [comment] 2019-07-30 20:44
> Full log, please

https://hasteb.in/odumoyis.md

> Please compress all configuration files in a zip and send it.

[Gloss.zip](https://github.com/VolmitSoftware/Mortar/files/3448783/Gloss.zip)

> Is the player near a hologram, does it occur when a player is not near a hologram? If it persists near a specific hologram please include that hologram's configuration file aswell. 

It does happen on multiple holograms and not just a single one.
I didn't check if it happens when the player is away from a hologram or not and I removed the plugin from the server for the moment.

> Are you using emojis in boards?

None of the holograms does use emojis.

**Comment by DavidRockin** [comment] 2019-07-30 23:31
Reworked emoji reload logic in 4558f02

**Closed as completed by DavidRockin** 2019-07-30 23:31 UTC
Labels: bug, IN-PROGRESS
